CSP-610-PopulateProfileDataInSessionModel
SkillsFundingAgency/das-apprentice-aan-web pull request #11
Opened 2023-03-13 15:06 UTC by ravihejmadi

This PR will not go out into Testing. It will be reviewed and pushed into main.
New ProfileService, GetProfilesResult, Profile.cs DomainModel 
Updated IOuterApiClient.cs, ServiceRegistrationsStartup.cs, BeforeYouStartController & Tests

2023-03-14 22:33 UTC, DevenKShah requested changes

2023-03-14 22:33 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Application.UnitTests/Services/ProfileServiceTests.cs
> +        var service = new ProfileService(_outerApiClient.Object);
Rename service to sut so it is easy to identify the test target. 

Also there should be spaces between Arrange / Act / Assert for readability

2023-03-14 22:33 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Application.UnitTests/Services/ProfileServiceTests.cs
> +        var result = await _outerApiClient.Object.GetProfilesByUserType(userType);
This works but it is not the correct way of doing things. You should do a setup on the client mock to return a pre-defined result. Then assert that the response received from the service calls is equivalent to the pre-defined set.

2023-03-14 22:33 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Models/OnboardingSessionModel.cs
> +    public string Category { get; set; } = null!;
You need to save description and order as well here.

2023-03-14 22:33 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/BeforeYouStartController.cs
> +        sessionModel.ProfileData = profiles.ConvertAll(p => new ProfileModel());
The conversion of data is not happening here, you will just get a list of empty objects. 
You need an implicit operator on ProfileModel to convert from Profile and then you can convert the list using select `profiles.Select(p => (ProfileModel)p).ToList()`

2023-03-14 22:33 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/BeforeYouStartControllerTests/BeforeYouStartControllerPostTests.cs
> +        sessionModel.ProfileData.Should().BeEquivalentTo(profiles.ConvertAll(p => new ProfileModel()));
There should not be a need to do the conversion here at all. I have added a comment on the actual code that will help remove any conversion in test.

2023-03-15 16:06 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Application.UnitTests/Services/ProfileServiceTests.cs
> +        var service = new ProfileService(_outerApiClient.Object);
Renamed service & Added new lines in-between

2023-03-15 16:07 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Models/OnboardingSessionModel.cs
> +    public string Category { get; set; } = null!;
Added Description and Ordering

2023-03-15 16:11 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/BeforeYouStartController.cs
> +        sessionModel.ProfileData = profiles.ConvertAll(p => new ProfileModel());
Modified this line and added an implicit conversion in the model [here](https://github.com/SkillsFundingAgency/das-apprentice-aan-web/blob/d07e4577a0a4b0f597816714a3e8a9da60ec7eab/src/SFA.DAS.ApprenticeAan.Web/Models/OnboardingSessionModel.cs#L32)

2023-03-15 16:12 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/BeforeYouStartControllerTests/BeforeYouStartControllerPostTests.cs
> +        sessionModel.ProfileData.Should().BeEquivalentTo(profiles.ConvertAll(p => new ProfileModel()));
Amended this line

2023-03-15 16:13 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Application.UnitTests/Services/ProfileServiceTests.cs
> +        var result = await _outerApiClient.Object.GetProfilesByUserType(userType);
This Unit Test has now been reworked. Thanks for you help with this.

2023-03-15 16:57 UTC, DevenKShah requested changes

2023-03-15 16:57 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/BeforeYouStartControllerTests/BeforeYouStartControllerPostTests.cs
> +        result.As<RedirectToRouteResult>().RouteName.Should().Be("TermsAndConditions");
User the RouteNames constant here

2023-03-15 16:57 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/BeforeYouStartControllerTests/BeforeYouStartControllerPostTests.cs
> +    }
```suggestion (fix any compile time issues)
    [MoqAutoData]
    public async Task Post_GetProfiles_UpdatesSessionModel(
        [Frozen] Mock<ISessionService> sessionServiceMock,
        [Frozen] Mock<IProfileService> profileServiceMock,
        [Greedy] BeforeYouStartController sut),
        List<Profile> profiles
    {
        const string userType = "apprentice";

        OnboardingSessionModel sessionModel = new();
        profileServiceMock.Setup(s => s..GetProfilesByUserType(userType)).ReturnsAsync(profiles);
        sessionServiceMock.Setup(s => s.Get<OnboardingSessionModel>()).Returns(sessionModel);
               
        await sut.PostAsync();

        sessionServiceMock.Verify(s => s.Set(sessionModel));

        sessionModel.ProfileData.Should().BeEquivalentTo(profiles));
    }
```

2023-03-15 16:57 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/BeforeYouStartController.cs
> +    public async Task<IActionResult> PostAsync()
Rename to `Post()`

2023-03-15 16:57 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/BeforeYouStartController.cs
> +        _sessionService.Set(sessionModel);
```suggestion
        var sessionModel = new OnboardingSessionModel();
        sessionModel.ProfileData = profiles.Select(p => (ProfileModel)p).ToList();
        _sessionService.Set(sessionModel);
```

2023-03-15 16:57 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Models/OnboardingSessionModel.cs
> +    public static implicit operator ProfileModel(Profile profile) => new()
Move ProfileModel into its own file and add coverage please.

2023-03-15 20:56 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/BeforeYouStartControllerTests/BeforeYouStartControllerPostTests.cs
> +        result.As<RedirectToRouteResult>().RouteName.Should().Be("TermsAndConditions");
Substituted with RouteNames constant

2023-03-15 20:58 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/BeforeYouStartControllerTests/BeforeYouStartControllerPostTests.cs
> +    }
Applied profileServiceMock.Setup & removed LINQ on last line. Compiler null error message has gone. Thanks :-)

2023-03-16 08:36 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/BeforeYouStartController.cs
> +    public async Task<IActionResult> PostAsync()
Renamed to Post

2023-03-16 08:37 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/BeforeYouStartController.cs
> +        _sessionService.Set(sessionModel);
@DevenKShah, I did this but then had to roll this back as [this](https://github.com/SkillsFundingAgency/das-apprentice-aan-web/pull/11#discussion_r1137440549) change would not work. Happy to discuss

2023-03-16 08:38 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Models/OnboardingSessionModel.cs
> +    public static implicit operator ProfileModel(Profile profile) => new()
Moved to its own class and added coverage

2023-03-17 16:36 UTC, merged