Csp 489 aan onboarding tell us country you work in
SkillsFundingAgency/das-apprentice-aan-web pull request #12
Opened 2023-03-15 21:55 UTC by YuvrajPatil-DFE

Implemented Regions controller and an empty CurrentJobTitle view to redirect to it on click on back button on Regions view

2023-03-20 11:05 UTC, DevenKShah requested changes

2023-03-20 11:05 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/RegionController.cs
> +        var model = new RegionViewModel
You should restore previous selection of regions if any from session model.

2023-03-20 11:05 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/RegionController.cs
> +        if (!result.IsValid)
If the result is not valid then it is required that we add the errors to the model state, so the validation errors can show on the page. I don't see where this is happening?

2023-03-20 11:54 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Views/Onboarding/CurrentJobTitle.cshtml
> +
Implemented

2023-03-20 11:55 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Views/Shared/_ValidationSummary.cshtml
> +                                                        <a href="#@propertyName">
Fixed

2023-03-20 11:56 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/RegionController.cs
> +public class RegionController : Controller
Changed

2023-03-20 11:56 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/CurrentJobTitleController.cs
> +        public CurrentJobTitleController()
Removed

2023-03-20 12:06 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Application.UnitTests/Services/RegionServiceTests.cs
> +        var regionService = new RegionService(outerApiClient.Object);
Renamed

2023-03-20 12:32 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/RegionController.cs
> +        var model = new RegionViewModel
Implemented

2023-03-20 12:33 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Application.UnitTests/Services/RegionServiceTests.cs
> +        result.Should().NotBeNullOrEmpty();
Implemented

2023-03-20 13:59 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Application.UnitTests/Services/RegionServiceTests.cs
> +        result.Should().NotBeNullOrEmpty();
Implemented

2023-03-22 11:31 UTC, DevenKShah reviewed
Few minor fixes required

2023-03-22 11:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/RegionsController.cs
> +        };
Repetitive code, should be a private method

2023-03-22 11:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerGetTests.cs
> +    public async Task Get_ViewModel_HasBackLink(
Add coverage for getting regions is missing

2023-03-22 11:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Application/Services/RegionsService.cs
The interface needs renaming as well to IRegionsService

2023-03-22 11:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerPostTests.cs
> +  [Frozen] Mock<ISessionService> sessionServiceMock,
alignment, please change your Visual studio setting to fix alignment on save

2023-03-22 11:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerPostTests.cs
> +  [Frozen] Mock<ISessionService> sessionServiceMock,
alignment

2023-03-22 11:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/RegionSubmitModelValidator.cs
Rename file to RegionsSubmitModelValidator

2023-03-22 12:07 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerPostTests.cs
> +  [Frozen] Mock<ISessionService> sessionServiceMock,
Redone the alignment manually.  I do have the same settings, somehow its now applying the way we want

2023-03-22 12:34 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerGetTests.cs
> +    public async Task Get_ViewModel_HasBackLink(
Implemented. Verified Backlink, Regions list and SelectedRegion if any.

2023-03-22 16:04 UTC, DevenKShah approved these changes

2023-03-24 15:45 UTC, DevenKShah approved these changes

2023-03-24 16:08 UTC, merged