CSP-1183 Upgrade .NET6 to .NET8
SkillsFundingAgency/das-apprentice-aan-web pull request #120
Opened 2024-02-12 14:57 UTC by ManishAgarwalDfE

2024-02-15 14:17 UTC, DevenKShah requested changes

2024-02-15 14:17 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Services/FilterBuilderTests.cs
> +        }
What is the point?

2024-02-15 14:17 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/NetworkEventDetailsControllerTests.cs
> +        var result = await sut.Post(calendarEventId, command, new CancellationToken());
why was this necessary?

2024-02-15 14:17 UTC, DevenKShah commented on src/SFA.DAS.Aan.SharedUi/SFA.DAS.Aan.SharedUi.csproj
>      <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
These are transitive dependencies, we can try remove its reference

2024-02-15 14:17 UTC, DevenKShah commented on src/SFA.DAS.Aan.SharedUi.UnitTests/SFA.DAS.Aan.SharedUi.UnitTests.csproj
> +	  <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
These are transitive dependencies, we can try remove its reference

2024-02-16 12:18 UTC, ManishAgarwalDfE commented on src/SFA.DAS.Aan.SharedUi/SFA.DAS.Aan.SharedUi.csproj
>      <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
Done

2024-02-16 12:19 UTC, ManishAgarwalDfE commented on src/SFA.DAS.Aan.SharedUi.UnitTests/SFA.DAS.Aan.SharedUi.UnitTests.csproj
> +	  <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
Done

2024-02-16 12:20 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Domain.UnitTests/SFA.DAS.ApprenticeAan.Domain.UnitTests.csproj
> +    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
Done

2024-02-16 12:22 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Application/Services/ApprenticeAccountService.cs
> +
Done

2024-02-16 12:23 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web/SFA.DAS.ApprenticeAan.Web.csproj
> +    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="8.0.0" />
Done

2024-02-16 12:24 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/NotificationsController.cs
> +        (string RouteName, object? RouteValues) = notification.TemplateName switch
Done

2024-02-16 12:24 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/LeaveTheNetworkController.cs
> +            LeavingBenefits = [.. leavingReasons.First(x => x.Category.Contains("benefit")).LeavingReasons.OrderBy(x => x.Ordering)],
Done

2024-02-16 12:25 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/EditAreaOfInterestController.cs
> +        [
Done

2024-02-16 12:26 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Api.MockServer/SFA.DAS.ApprenticeAan.Api.MockServer.csproj
>      <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
Done

2024-02-16 12:27 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Application/SFA.DAS.ApprenticeAan.Application.csproj
>      <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
Done

2024-02-16 12:28 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/SFA.DAS.ApprenticeAan.Web.UnitTests.csproj
>      <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
Done

2024-02-16 12:52 UTC, ManishAgarwalDfE commented on src/SFA.DAS.Aan.SharedUi/Views/NetworkEventDetails/Detail.cshtml
> -                        <input type="hidden" asp-for="@Model.CalendarEventId"/>
Reverted I did this because I changed the logic to get calendar event id from route instead of model as sonarqube was complaining about the unused parameter. The parameter was never used but I agree there would be a larger impact i.e. on Employer web.

2024-02-16 12:54 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Domain/SFA.DAS.ApprenticeAan.Domain.csproj
> +    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
Done

2024-02-16 12:55 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web/SFA.DAS.ApprenticeAan.Web.csproj
> +    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.3.1" />
I've tested the code several times and nothing is failing. I will keep an eye

2024-02-16 13:02 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Services/FilterBuilderTests.cs
> +        }
In FilterBuilder.cs => BuildQueryParameters method , sonarqube is complaining for less coverage for so to cover the test case which is missing, I have added this data to the Status property.

2024-02-16 13:03 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/NetworkEventDetailsControllerTests.cs
> +        var result = await sut.Post(calendarEventId, command, new CancellationToken());
This is again the same reason - parameter was never used affecting the tests. I have reverted it back.

2024-02-16 14:47 UTC, ManishAgarwalDfE commented on src/SFA.DAS.Aan.SharedUi/Views/LeaveTheNetwork/Index.cshtml
> +                                        <label class="govuk-label govuk-checkboxes__label" asp-for="@Model.LeavingReasons[@i].IsSelected">
Fixed checkbox problem on 3 pages - Member Profile (Edit area of interest), Onboarding journey (Area of interest) and leaving the network page.

2024-02-16 16:24 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Services/FilterBuilderTests.cs
> +        }
But you are not asserting the effect of the data being set or the fact that this is set, there should be some assertion.

2024-02-16 16:28 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/README.md
Readme is already there in the root of the repository

2024-02-16 16:30 UTC, DevenKShah requested changes
Readme is already there, delete what you have added, and update the existing one.

2024-02-16 16:45 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web/README.md
Done

2024-02-19 08:15 UTC, DevenKShah approved these changes

2024-02-19 08:15 UTC, DevenKShah commented on README.md
> +Users are expected to register themselves in the Apprentice portal. Once registered they will have access to on-boarding journey for AAN. Users who are already apprentices will also have access to on
There is no stub sign in here is there?

2024-02-19 08:50 UTC, ManishAgarwalDfE commented on README.md
> +Users are expected to register themselves in the Apprentice portal. Once registered they will have access to on-boarding journey for AAN. Users who are already apprentices will also have access to on
Done

2024-02-20 13:41 UTC, DevenKShah commented on src/SFA.DAS.Aan.SharedUi/Views/Error/ErrorInService.cshtml
> +            Refresh your browser, or return to the <a asp-action="Index" asp-controller="home">training provider dashboard</a>
`training provider dashboard` is incorrect, instead say `apprentice ambassador network home`

2024-02-20 13:41 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Program.cs
> +app.UseExceptionHandler("/error");
This should be inside the if condition so that in debug mode we can see the actual error page with error details

2024-02-20 13:41 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Program.cs
> +        context.Request.Path = "/error/404";
Have you tested this working?

2024-02-20 14:45 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Program.cs
> +    app.UseExceptionHandler("/error");
This should be in the else part

2024-02-20 15:09 UTC, ManishAgarwalDfE commented on src/SFA.DAS.ApprenticeAan.Web/Program.cs
> +    app.UseExceptionHandler("/error");
Done

2024-02-20 16:22 UTC, DevenKShah approved these changes

2024-02-23 10:29 UTC, merged