CSP-532-AANOnboarding-EmployerAddress_MANUAL-ENTRY
SkillsFundingAgency/das-apprentice-aan-web pull request #13
Opened 2023-03-20 16:32 UTC by ravihejmadi

Introduced - Controller, Model, Validator & Tests
Modified - Linemanager Controller
Changes made to Web & Test projects only

2023-03-24 13:06 UTC, DevenKShah requested changes

2023-03-26 13:04 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Domain/OuterApi/Responses/Profile.cs
> +        public Int16 Id { get; set; }
This was mistakenly committed into the branch and was modified when experimenting comparison with `Enums`. It had been rolled back before the code-review and so should not have appeared here. Nevertheless it is resolved

2023-03-26 13:04 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Infrastructure/RouteNames.cs
> +        public const string CreateEmployer = nameof(CreateEmployer);
Changed to `EmployerDetails` here and elsewhere as applicable

2023-03-26 13:05 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/EmployerController.cs
> +    [Route("onboarding/create-employer", Name = RouteNames.Onboarding.CreateEmployer)]
Changed to `employer-details` here and elsewhere as applicable

2023-03-26 13:07 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/CreateEmployerSubmitModelValidator.cs
> +        RuleFor(e => e.AddressLine1)
This is now 200 for EmployerName, Address1 & 2  + County. Town remains 50 and Postcode stays 8

2023-03-26 13:07 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/CreateEmployerSubmitModelValidator.cs
> +            .MaximumLength(256);
This is now 200

2023-03-26 13:08 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/CreateEmployerSubmitModelValidator.cs
> +
Added length validation for County and AddressLine2

2023-03-26 13:09 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Validators/Onboarding/CreateEmployerSubmitModelValidatorTests.cs
> +        public void Validates_EmployerName_Length(int length, bool isValid)
This is already the case

2023-03-27 07:41 UTC, DevenKShah approved these changes

2023-03-27 07:41 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/EmployerControllerTests/EmployerControllerAttributeTests.cs
> +            httpGetMethod.Should().BeDecoratedWith<RouteAttribute>().Subject.Name.Should().Be("EmployerDetails");
The dependency is on the const variable and not the value of the variable, so we should use RouteNames  constant here.

2023-03-27 07:41 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/EmployerDetailsSubmitModelValidator.cs
> +    public const string PostcodeInvalidMessage = "Enter a real postcode";
Please is missing here?

2023-03-27 07:41 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Validators/Onboarding/EmployerDetailsSubmitModelValidatorTests.cs
> +                result.ShouldHaveValidationErrorFor(c => c.Postcode);
Where postcode is invalid, there is a different message to when postcode is missing, hence we should verify the message for failing tests.

2023-03-27 08:26 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/EmployerControllerTests/EmployerControllerAttributeTests.cs
> +            httpGetMethod.Should().BeDecoratedWith<RouteAttribute>().Subject.Name.Should().Be("EmployerDetails");
Reverted to `constant`. Thanks for spotting this.

2023-03-27 08:27 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/EmployerDetailsSubmitModelValidator.cs
> +    public const string PostcodeInvalidMessage = "Enter a real postcode";
Amended as recommended

2023-03-27 08:29 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Validators/Onboarding/EmployerDetailsSubmitModelValidatorTests.cs
> +                result.ShouldHaveValidationErrorFor(c => c.Postcode);
Created separate test for Invalid postcode and am now checking for messages with a `WithErrorMessage` check

2023-03-27 08:36 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/EmployerControllerTests/EmployerControllerPostTests.cs
> +        sut.ModelState.IsValid.Should().BeTrue();
The reasoning is because IsValid is being checked as the pivot point for any further action. The point would make sense when seen from [here](https://github.com/SkillsFundingAgency/das-apprentice-aan-web/blob/7923a29b556144da770fdaeda504a2b6c7dca217/src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/EmployerControllerTests/EmployerControllerPostTests.cs#L58).

2023-03-27 08:47 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/EmployerControllerTests/EmployerControllerPostTests.cs
> +        sut.ModelState.IsValid.Should().BeTrue();
Is the value os IsValid changing as part of this update to session model?

2023-03-27 09:24 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/EmployerControllerTests/EmployerControllerPostTests.cs
> +        sut.ModelState.IsValid.Should().BeTrue();
Marking as resolved since we agreed `IsValid `check is need within this test as it is a part of the `SubmitModel`

2023-03-29 13:48 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Application/Constants.cs
> +            public const string EmailRegex = @"^[-!#$%&'*+/0-9=?A-Z^_a-z{|}~](\.?[-!#$%&'*+/0-9=?A-Z^_a-z{|}~])*@[a-zA-Z0-9_](-?[a-zA-Z0-9_])*(\.[a-zA-Z0-9](-?[a-zA-Z0-9])*)+$";
Remove unused regex

2023-03-29 13:48 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/EmployerControllerTests/EmployerControllerAttributeTests.cs
> +            httpGetMethod.Should().BeDecoratedWith<RouteAttribute>().Subject.Name.Should().Be(RouteNames.Onboarding.EmployerDetails);
Fix test

2023-03-29 13:48 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/EmployerController.cs
> +    [Route("onboarding/employer-details", Name = RouteNames.Onboarding.EmployerDetails)]
Move Route attribute at the class level

2023-03-29 13:48 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/EmployerDetailsSubmitModelValidator.cs
> +    private const string ValidCharactersExpression = @"^[^@#$^=+\\\/<>%]*$";
Move `ValidCharactersExpression` to Application Constants so we can use this in other places and rename this to `ExcludedCharactersRegex`

2023-03-29 15:05 UTC, DevenKShah submitted a review, later dismissed

2023-04-04 10:19 UTC, merged