CSP-532-AANOnboarding-OnboardingSessionModel
SkillsFundingAgency/das-apprentice-aan-web pull request #16
Opened 2023-03-22 13:49 UTC by ravihejmadi

OnboardingSessionModel.cs - contains ExtensionMethods OnboardingSessionModelTests.cs - contains additional tests & conditional checks for ProfileData i.e. List<ProfileModel>

2023-03-22 14:03 UTC, DevenKShah requested changes

2023-03-22 15:41 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Models/OnboardingSessionModel.cs
> +    public static IEnumerable<ProfileModel> UpdateProfileModelValue(this List<ProfileModel> profileItems, int id, string? value)
Updated Line#32. Also tested successfully in CSP-532 Employee branch.

2023-03-22 15:41 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Models/OnboardingSessionModel.cs
> +    public static string GetProfileModelValue(this List<ProfileModel> profileItems, int id)
Updated to nullable as advised

2023-03-22 15:42 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Models/OnboardingSessionModelTests.cs
> +    private static readonly List<Profile>? profiles = new()
Now set to `List<ProfileModel>`

2023-03-23 07:37 UTC, DevenKShah approved these changes

2023-03-23 09:32 UTC, MarkFCain approved these changes

2023-03-23 09:33 UTC, merged