CSP-490-AANOnboarding-JoinTheNetwork
SkillsFundingAgency/das-apprentice-aan-web pull request #19
Opened 2023-03-30 13:30 UTC by ravihejmadi

Introduced - Controller, Model, Validator & Tests
Modified - CurrentJobTitle Controller
Changes made to Web & Test projects only

2023-03-30 21:21 UTC, DevenKShah approved these changes
Looks good. I have added few minor improvement suggestions and couple of queries.

2023-03-30 21:21 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/JoinTheNetworkControllerTests/JoinTheNetworkControllerGetTests.cs
> +        result.As<ViewResult>().Should().NotBeNull();
This is implicitly covered in the next test where you are checking for ViewPath

2023-03-30 21:21 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/JoinTheNetworkControllerTests/JoinTheNetworkControllerPostTests.cs
> +        sessionModel.HasEmployersApproval.Should().BeNull();
What is this check for?

2023-03-31 08:40 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/CurrentJobTitleController.cs
> -        //remomve below line when next page link is configured.
I can't as it is used [here](https://github.com/SkillsFundingAgency/das-apprentice-aan-web/blob/5d000e63ff01386ff8fb64e23c0d6e17ed611654/src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/CurrentJobTitleController.cs#L39)

2023-03-31 08:42 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Views/Onboarding/JoinTheNetwork.cshtml
> +    var maxWordCount = 250;
Done. It had to be added into the Submit model so it could be used in the Validator

2023-03-31 08:42 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/JoinTheNetworkSubmitModelValidator.cs
> +        const int MaxWords = 250;
Done

2023-03-31 08:43 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/CurrentJobTitleController.cs
> -        //remomve below line when next page link is configured.
I am asking you make changes in the Post method only. Refer the line numbers

2023-03-31 08:56 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/JoinTheNetworkControllerTests/JoinTheNetworkControllerGetTests.cs
> +        result.As<ViewResult>().Should().NotBeNull();
Removed as advised.

2023-03-31 08:56 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/JoinTheNetworkControllerTests/JoinTheNetworkControllerPostTests.cs
> +        sessionModel.HasEmployersApproval.Should().BeNull();
Sorry overlooked here. Now removed

2023-04-04 14:48 UTC, MarkFCain submitted a review, later dismissed

2023-04-04 16:13 UTC, DevenKShah requested changes

2023-04-05 15:51 UTC, DevenKShah submitted a review, later dismissed

2023-04-11 14:25 UTC, DevenKShah submitted a review, later dismissed

2023-04-12 11:27 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/ReasonToJoinSubmitModelValidator.cs
> +using System.Drawing.Text;
Remove unused namespace

2023-04-12 12:11 UTC, YuvrajPatil-DFE approved these changes

2023-04-12 12:13 UTC, ravihejmadi commented on src/SFA.DAS.ApprenticeAan.Web/Validators/Onboarding/ReasonToJoinSubmitModelValidator.cs
> +using System.Drawing.Text;
Removed

2023-04-12 15:23 UTC, merged