CSP 491 areas of interest
SkillsFundingAgency/das-apprentice-aan-web pull request #22
Opened 2023-04-04 16:58 UTC by YuvrajPatil-DFE

As an apprentice I want to highlight my areas of interest in the AAN. So that when I am registered as an AAN member I can be made aware of events that most suit my interests.

I have implemented controller, view, model and test cases

2023-04-05 10:31 UTC, DevenKShah requested changes

2023-04-05 10:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Validators/Onboarding/AreasOfInterestModelValidatorTests.cs
> +    public void EventsSelection_Validation_NoError()
Validate_EventSelected_Valid... convention is `Subject<OrAction>_Condition_Result`

2023-04-05 10:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Validators/Onboarding/AreasOfInterestModelValidatorTests.cs
> +    public void PromotionsSelection_Validation_NoError()
same here... Validate_PromotionSelected_Valid

2023-04-05 10:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Validators/Onboarding/AreasOfInterestModelValidatorTests.cs
> +    public void NoSelection_Validation_Error()
Validate_NoSelection_Invalid

2023-04-05 10:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/AreasOfInterestControllerTests/AreasOfInterestControllerGetTests.cs
> +        result.As<ViewResult>().Model.As<AreasOfInterestViewModel>().AreasOfInterest.Should().NotBeNull();
We need more deterministic test here. Populate events and promotion and validate AreasOfInterest has all the elements.

2023-04-05 10:31 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/AreasOfInterestControllerTests/AreasOfInterestControllerPostTests.cs
> +            Events = new List<SelectProfileModel> { new SelectProfileModel { Id = 1, IsSelected = false } },
Change one of this to true and add an assert accordingly. Interesting thought, I think we will have to clear all the values in case the user navigates back to this page and updates selection.

2023-04-05 15:08 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/AreasOfInterestController.cs
> +            sessionModel.SetProfileValue(x.Id, x.IsSelected.ToString());
But if user selects lets say 1st, 3rd and 4th item. Then comes back to this page and deselects 3rd one. We need to save this back to false (or may be null) that's why not considering only IsSelected to true

2023-04-05 15:16 UTC, alandburns commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/AreasOfInterestController.cs
> +            sessionModel.SetProfileValue(x.Id, x.IsSelected.ToString());
We will only save the persisted collected values during the on-boarding session.
Later in the Profile UI feature we will need to handle where a member changes a profile setting and may set a true to false.

2023-04-06 10:49 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Models/SelectProfileModel.cs
> +        Value = profile.Value
I may be confused, but I don't see why we need Value field in the SelectProfileModel, we should restore IsSelected from the Profile.Value instead. Also I think when user comes back to this page, the checks boxes will not be preselected as we are not restoring IsSelected here.

2023-04-06 14:23 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Models/SelectProfileModel.cs
> +        Value = profile.Value
Removed Value field

2023-04-11 09:58 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/AreasOfInterestController.cs
> +            x.IsSelected = Convert.ToBoolean(sessionModel.GetProfileValue(x.Id));
This can be moved in to implicit operator in SelectProfileModel, this will avoid the extra looping through here.

2023-04-12 09:54 UTC, MarkFCain commented on src/SFA.DAS.ApprenticeAan.Web/Views/Onboarding/AreasOfInterest.cshtml
> +                                for (int i = 0; i < Model.Events.Count; i++)
Can you update to use foreach here?

2023-04-12 09:54 UTC, MarkFCain approved these changes
have a look at the for loops in the view, I think foreach is more readable

2023-04-12 10:03 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web/Views/Onboarding/AreasOfInterest.cshtml
> +                                for (int i = 0; i < Model.Promotions.Count; i++)
Keeping it as it is as getting some issue in validating if changed to foreach loop

2023-04-12 10:05 UTC, DevenKShah approved these changes

2023-04-12 14:16 UTC, MarkFCain approved these changes

2023-04-12 17:19 UTC, DevenKShah approved these changes

2023-04-17 08:26 UTC, merged