CSP-667-Implemented View, Controller, TC
SkillsFundingAgency/das-apprentice-aan-web pull request #26
Opened 2023-04-12 17:20 UTC by YuvrajPatil-DFE

2023-04-13 21:49 UTC, DevenKShah requested changes

2023-04-13 21:49 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerGetTests.cs
> +        sut.AddUrlHelperMock().AddUrlForRoute(sessionModel.HasSeenPreview ? RouteNames.Onboarding.CheckYourAnswers : RouteNames.Onboarding.CurrentJobTitle);
We need to add specific tests for Backlink for both case where HasSeenPreview is true and false.

2023-04-13 21:49 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Models/CheckYourAnswersViewModelTests.cs
> +        mockUrlHelper.AddUrlForRoute(RouteNames.Onboarding.Regions);
Need to override default url here

2023-04-13 21:49 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web/Controllers/Onboarding/RegionsController.cs
>          return RedirectToRoute(RouteNames.Onboarding.ReasonToJoin);
On post we need to navigate back to CheckYourAnswers if HasSeenPreview is true

2023-04-17 09:15 UTC, MarkFCain reviewed
Please add coverage asked for, I don't see any other issues

2023-04-18 07:21 UTC, MarkFCain approved these changes

2023-04-18 08:01 UTC, DevenKShah commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerPostTests.cs
> +    public async Task Post_Regions_RedirectsToCheckYourAnswers(
Post_IsValidAndHasSeenPreview_RedirectsToCheckYourAnswers

2023-04-18 08:06 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerGetTests.cs
> +    public async Task Get_ViewModelHasSeenPreviewIsFalse_RedirectsRouteToCurrentJobTitle(
Renamed to Get_ViewModelHasSeenPreviewIsFalse_BankLinkSetsToToCurrentJobTitle

2023-04-18 08:08 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.ApprenticeAan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerGetTests.cs
> +    public async Task Get_ViewModelHasSeenPreviewIsTrue_RedirectsRouteToCheckYourAnswers(
Get_ViewModelHasSeenPreviewIsTrue_BankLinkSetsToCheckYourAnswers

2023-04-18 08:45 UTC, DevenKShah submitted a review, later dismissed

2023-04-18 08:59 UTC, DevenKShah approved these changes

2023-04-19 11:04 UTC, merged